services:
  ngxman:
    container_name: ngxman
    image: ad3m3r5/ngxman:latest
    restart: unless-stopped
    ports:
      - "80:8080"
      - "443:8443"
      - "3000:3000"
    environment:
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/data
